export const flags = [
  { src: "국민이 주인이다.png" },
  { src: "대구 경북의 딸.png" },
  { src: "도리깨 한국 협회지부.png" },
  { src: "돈없고 병든 예술인 연합.png" },
  { src: "만두노총 군만두노조.png" },
  { src: "무인도 주민 대표 연합.png" },
  { src: "불꽃남자 정대만.png" },
  { src: "붕어팥속팥검열단.png" },
  { src: "서울인권영화제.png" },
  { src: "신지 에바에서 내려라 연합.png" },
  { src: "쌍도의딸.png" },
  { src: "야생맘마먹음이보존협회.png" },
  { src: "전국 제다이 연합.png" },
  { src: "지속 가능한 덕질.png" },
  { src: "포스타입 분서갱유 반대연합.png" },
  { src: "학생 사회주의자 연대.png" },
  { src: "행복한 크리스마스를 바라는 가족 연합.png" },
];
